[package]
name = "Generety"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.31", features = ["glow", "persistence"] }
egui_plot = "0.32.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
